# Generated by Django 3.1 on 2020-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('povis_id', models.CharField(max_length=100, verbose_name='POVIS ID')),
                ('items', models.ManyToManyField(blank=True, to='roulette.Item', verbose_name='획득한 상품들')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
            },
        ),
    ]
