# Generated by Django 3.1 on 2020-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_auto_20200901_1855'),
        ('core', '0002_auto_20200901_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='roulette.Round', verbose_name='참여한 라운드'),
        ),
    ]
