# Generated by Django 3.1 on 2020-09-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200912_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['povis_id'], 'verbose_name': '유저', 'verbose_name_plural': '유저들'},
        ),
    ]
