# Generated by Django 3.1 on 2020-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='아이템 이름')),
                ('probability', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='확률 (0~1)')),
                ('num', models.IntegerField(verbose_name='재고')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='라운드')),
                ('start_time', models.DateTimeField(verbose_name='시작 시각')),
                ('end_time', models.DateTimeField(verbose_name='끝 시각')),
            ],
        ),
    ]
