# Generated by Django 3.1 on 2020-09-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200901_1855'),
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(to='core.User', verbose_name='당첨자'),
        ),
        migrations.AlterField(
            model_name='item',
            name='probability',
            field=models.DecimalField(decimal_places=9, max_digits=10, verbose_name='확률 (0~1)'),
        ),
    ]
