# Generated by Django 3.1 on 2020-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200912_2000'),
        ('roulette', '0002_auto_20200901_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name': '라운드', 'verbose_name_plural': '라운드들'},
        ),
        migrations.AlterField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(blank=True, to='core.User', verbose_name='당첨자'),
        ),
    ]
