# Generated by Django 3.1 on 2020-09-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_auto_20200912_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['start_time'], 'verbose_name': '라운드', 'verbose_name_plural': '라운드들'},
        ),
    ]
