# Generated by Django 3.1 on 2020-09-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_auto_20200912_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(default='gs.png', max_length=100, verbose_name='이미지 이름'),
            preserve_default=False,
        ),
    ]
